swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: account-controller
    description: Account Controller
paths:
  /v1/api/accounts/register:
    post:
      tags:
        - account-controller
      summary: Register a new account to the application
      description: 'User can create an account in the application. He/she can create it without login '
      operationId: signUpUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: registerDto
          description: registerDto
          required: true
          schema:
            $ref: '#/definitions/RegisterUserDto'
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /v1/api/accounts/users:
    get:
      tags:
        - account-controller
      summary: List the users associated with an account
      description: ' Account user must login into the application.  Find the token in response header and use that token in Authorization header ( Bearer <your token>)'
      operationId: getUsersUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  RegisterUserDto:
    type: object
    properties:
      mobileNo:
        type: string
      password:
        type: string
      userName:
        type: string
    title: RegisterUserDto
